# Generated by Django 3.1.5 on 2021-12-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
