# Generated by Django 3.1.5 on 2021-12-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctie', '0002_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
