# Generated by Django 3.1.5 on 2021-12-23 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctie', '0003_auto_20211217_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_made',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=200, null=True)),
                ('agent', models.CharField(max_length=200, null=True)),
                ('shipby', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctie.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ctie.order')),
            ],
        ),
    ]
