# Generated by Django 3.1.5 on 2021-12-23 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctie', '0004_orders_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_made',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
