# Generated by Django 3.1.5 on 2021-12-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctie', '0005_orders_made_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_made',
            name='date_added',
        ),
    ]
