# Generated by Django 3.1.5 on 2021-12-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctie', '0006_remove_orders_made_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Electronics', 'Electronics'), ('Machines', 'Machines'), ('Household', 'Household')], max_length=15, null=True),
        ),
    ]
